---
- hosts: all
  gather_facts: no
  tasks:
    - name: "Create AWS S3 bucket {{ bucket_name }}"
      s3_bucket:
        name: "{{ bucket_name }}"
        region: "{{ region }}"

    - name: Set attributes
      set_stats:
        data: { bucket_name: "{{ bucket_name }}" }
...
