---
- hosts: all
  gather_facts: no
  tasks:
    - name: "Delete Lambda AWS role : {{ role_name }}"
      iam_role:
        state: absent
        name: "{{ role_name }}"
        region: "{{ region }}"
        assume_role_policy_document: "{{ lookup('file','policy.json') }}"
        managed_policy:
          - arn:aws:iam::aws:policy/AWSLambda_FullAccess
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      register: iam_role_response
...
