---
- hosts: all
  gather_facts: no
  tasks:
    - name: Remove VPC subnet
      amazon.aws.ec2_vpc_subnet:
        state: absent
        vpc_id: "{{ vpc_subnet_id }}"
        region: "{{ region }}"
        cidr: 10.0.0.0/24

    - name: Delete VPC
      amazon.aws.ec2_vpc_net:
        state: absent
        name: Thumbnail-VPC
        cidr_block: 10.0.0.0/24
        region: "{{ region }}"
...
