---
- hosts: all
  gather_facts: no
  tasks:
    - name: "Remove S3 bucket {{ bucket_name }}"
      s3_bucket:
        name: "{{ bucket_name }}"
        region: "{{ region }}"
        state: absent
        force: yes
...
