---
- hosts: all
  gather_facts: no
  tasks:
    - name: Install prerequsiste packages
      pip:
        chdir: "function"
        requirements: "requirements.txt"
        extra_args: "-t ."

    - name: Compress function an requirements into zip file
      archive:
        format: zip
        path: "function/"
        dest: "function.zip"

    - name: "Lambda {{ function_name }} deploy with env vars"
      lambda:
        name: "{{ function_name }}"
        zip_file: "function.zip"
        runtime: "{{ lambda_runtime }}"
        region: "{{ region }}"
        role: "{{ aws_role }}"
        handler: "{{ lambda_handler }}"
        timeout: "{{ lambda_timeout }}"
        memory_size: "{{ lambda_memory }}"
        environment_variables:
          BUCKET_OUT_NAME: "{{ bucket_out_name }}"
      register: lambda_info

    - name: Create function alias name
      lambda_alias:
        function_name: "{{ function_name }}"
        name: "{{ func_alias }}"
        region: "{{ region }}"
      register: alias_info

    - name: "Add invocation permission of Lambda function on AWS : {{ permission_id }}"
      lambda_policy:
        function_name: "{{ function_name }}"
        statement_id: "{{ permission_id }}"
        action: lambda:InvokeFunction
        region: "{{ region }}"
        alias: "{{ func_alias }}"
        principal: "s3.amazonaws.com"

    - name: Set attributes
      set_stats:
        data:
          function_arn: "{{ alias_info.alias_arn }}"
...
