---
- hosts: all
  gather_facts: no
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_file }}"
    ansible_ssh_user: "{{ ssh_user }}"
  tasks:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Place temporary file
      copy:
        dest: /tmp/opera.mark
        content: "{{ marker }}"
