---
- hosts: all
  gather_facts: no
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_file }}"
    ansible_ssh_user: "{{ ssh_user }}"
  tasks:
    - name: Stop nginx
      service:
        name: nginx
        enabled: no
        state: stopped

    - name: Uninstall nginx
      package:
        name: nginx
        state: absent
