---
- hosts: all
  gather_facts: no
  tasks:
    - name: "Delete EC2 AWS role : {{ role_name }}"
      iam_role:
        state: absent
        name: "{{ role_name }}"
        region: "{{ region }}"
        assume_role_policy_document: "{{ lookup('file','policy.json') }}"
        managed_policy:
          - arn:aws:iam::aws:policy/AmazonS3FullAccess
      register: iam_role_response
...
