---
- hosts: all
  gather_facts: no
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_file }}"
    ansible_ssh_user: "{{ ssh_user }}"
  tasks:
    - name: Install sample site
      copy:
        dest: "{{ item }}"
        content: |
          <!doctype html>
          <html lang="en">
          <head>
            <title>Hello World!</title>
          </head>
          <body>
            <h1>Sample we page</h1>
            <p>With little content ;)</p>
          </body>
          </html>
      with_items:
        - /var/www/html/index.html
        - /usr/share/nginx/html/index.html
