---
- hosts: all
  gather_facts: no
  tasks:
    - name: Remove prerequsiste packages
      pip:
        name:
          - botocore
          - boto3
          - boto
          - awscli
        state: absent
...
