---
- hosts: all
  gather_facts: no
  tasks:
    - name: Create a new EC2 security group
      amazon.aws.ec2_group:
        name: "{{ security_group }}"
        description: Thumbnail generator EC2 security group
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
              - 443
            cidr_ip: 0.0.0.0/0
      register: ec2_group

    - name: Launch a new EC2 instance
      amazon.aws.ec2:
        key_name: "{{ ssh_key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        group: "{{ security_group }}"
        instance_profile_name: "{{ role_instance_profile }}"
        wait: yes
        assign_public_ip: yes
      register: ec2

    - name: Set attributes
      set_stats:
        data:
          public_address: "{{ ec2.instances[0].public_dns_name }}"
          private_address: "{{ ec2.instances[0].private_dns_name }}"
          instance_id: "{{ ec2.instance_ids[0] }}"
          group_id: "{{ ec2_group.group_id }}"

    - name: Create temporary inventory for ssh wait
      add_host:
        name: server
        groups: vms
        ansible_host: "{{ ec2.instances[0].public_dns_name }}"
        ansible_user: "{{ ssh_user }}"
        ansible_ssh_private_key_file: "{{ ssh_key_file }}"
        ansible_ssh_common_args: >
          -o IdentitiesOnly=yes
          -o BatchMode=yes
          -o UserKnownHostsFile=/dev/null
          -o StrictHostKeyChecking=no

- hosts: vms
  gather_facts: no
  tasks:
    - name: Wait for ssh on EC2 instance to come up
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 120
...
