name: validate

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
          cache: 'pip'

      - name: Install preprequisites
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade opera-tosca-parser

      - name: Run validation script
        run: ./validate.sh opera-tosca-parser
