name: Validate examples with xOpera orchestrator

on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install preprequisites
        run: |
          python -m pip install --upgrade pip
          pip install opera
      - name: Run validation script
        run: ./validate.sh opera
